### ISSUE TITLE
 Issues of the old security audit

### ISSUE THREAD

**Issue by elrido** [PrivateBin/PrivateBin#20]
@rugk:

I noticed there was [a security audit](https://defuse.ca/audits/zerobin.htm) and some issues were fixed. I just [fixed another simple documentation issue](https://github.com/elrido/ZeroBin/wiki/Installation/_compare/5b42c2955b37264199314ef0965eb66c336b2c2c...327c5d62947186593c81ea75906e30c0491c4fb3) (2.6.).

So @elrido, your last statement [about this was](https://github.com/elrido/ZeroBin/issues/8):
> Most points referring to server side issues have been addressed (that's 2.1, 2.3, 2.7, 2.8). The rest is still open for debate or resolution.

So were any other issues fixed already?

----

Current state:

* [x] 2.1. Salt and HMAC Key Generated with mt_rand() - *fixed*
* [x] 2.2. Fixed Server Salt
* [x] 2.3. Traffic Limiter Race Conditions - *fixed*
* [ ] 2.4. VizHash IP Address Online Guessing
* [x] 2.5. Relies on .htaccess files, which may not be enabled. - Doc [addresses this issue](https://github.com/elrido/ZeroBin/wiki/Installation#changing-the-path) 
* [x] 2.6. The robots.txt does not work in a subdomain. - [fixed](https://github.com/elrido/ZeroBin/wiki/Installation/_compare/5b42c2955b37264199314ef0965eb66c336b2c2c...327c5d62947186593c81ea75906e30c0491c4fb3)
* [x] 2.7 HMAC Not Compared in Constant Time - *fixed*
* [x] 2.8. Arbitrary File Unlink - *fixed*
* [x] 2.9. HMAC Uses SHA1 instead of SHA256 - [*fixed*](https://github.com/elrido/ZeroBin/commit/0e217a42c5b53648e05f37dd08a66c01b7ff2022)
* [x] 2.10. No Cross-Site Request Forgery Protection - *moved* to #39
* [x] 3.1. Always Assume Malice - *partially fixed*, *ignored*, minor issue 
* [x] 4.1. Secure Code Delivery - [known, unsolveable](https://github.com/elrido/ZeroBin/issues/8)
* [ ] 4.2. urls2links XSS
* [x] 4.3. Low Entropy in Browsers Without CSPRNGs - *ignored*, only affects old clients
* [x] 4.4. Plaintext is Compressed Before Encryption - *ignored*, not applicable in our case, moved to #38
* [ ] 4.5. Is SJCL used correctly?
* [ ] 4.6. Possible XSS in tpl/page.html

---

@elrido:

I revisited the open points. Here is my opinion on it:

2.2 - Could be solved with a per paste salt.

2.4 - Inherent problem by doing any hashing of the IPs. Add an option to turn vizhash off?

2.9 - Could be changed very easily, but would break all existing delete links. We could make this an option and if enabled also use a per paste salt.

2.10 - We could implement a [Cookie-to-Header Token](https://en.wikipedia.org/wiki/Cross-site_request_forgery#Cookie-to-Header_Token).

3.1 - When I added unit testing I tried to add tests for weird and unexpected strings and subsequently had to improve the input handling. I would like to consider this solved, but there might be something I missed.

4.2 - I haven't found a way to trigger an XSS eighter, but that does not mean that there isn't any. Would consider this to be at least still a risky piece of code.

4.3 - We could add the server based randomness as a fallback. It is mainly an issue with [older browsers and on Android](https://developer.mozilla.org/de/docs/Web/API/RandomSource/getRandomValues#Browser_Compatibility)

4.4 - If we removed this it would break backwards compatibility, so we would need to make it an option (maybe we should just add a single "support old ZeroBin" option ;-) ).

4.5 - Well... We do use it as per their documentation. Maybe we should ask the SJCL devs if they could have a look and if they had any suggestions for improvements in our usage of it?

4.6 - The JSON  and the non encrypted options get generated server side. We should check if one could inject JS that gets executed into a validated encrypted part.

---

@rugk:

2.4 - Maybe just use another value instead of the IP for the visual hashing.. Let's say, ehm... user agent? I doubt this is better, so... What about:
* just using the entered username? (I'd prefer this)
* using a long-living cookie?

Of course making it optional is a good idea too.

2.9 - Yes, please. When used in HMAC SHA-1 is still secure, but I'd rather prefer SHA-256. MQybe switch this with the switch to a [new name](https://github.com/elrido/ZeroBin/issues/79)?

3.1 - As it also only is a potential attack (as the values are hashed and stuff...) I'd tick it here.

4.2. Use (switch?) to a [well-tested RegExp](https://stackoverflow.com/questions/205923/best-way-to-handle-security-and-avoid-xss-with-user-entered-urls#answer-205967) for this?

4.3 - I don't think adding server-randomness is a good idea. And as you said it also only affects older browsers. So I#d tick this as it is obsolete.

4.4 - Also implement when switching to a new name?

4.5 - Yeah, maybe.

4.6. - According to https://github.com/elrido/ZeroBin/issues/84 HTML is correctly encoded there.

---

@elrido:

Ok, I agree, but I really would like to still offer the possibility for easy upgrade to this fork from the old version. How about making it simple and offer a single option for (less safe) backwards compatibility (disabled by default)? Would also simplify the upgrade wiki page.

---

@rugk:

Yes, I'm all for options. :smiley: 

---

@elrido committed 0e217a4, resolving points 2.2 & 2.9

**Comment by rugk** [comment]
Subissues, which should be solved for milestone ["Next release"](https://github.com/PrivateBin/PrivateBin/milestone/1): 2.4

All other subissues should be moved to separate issues or somehow addressed, so we can close this issue. I've already done this with a few issues.
